#include <assert.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <signal.h>
#include <unistd.h>
#include <errno.h>
#include <time.h>

#include "gthr.h"
#include "gthr_struct.h"


void gt_alarm_handle(int sig) {
	gt_schedule();
}


void gt_statistics_handler(int sig) {
	printf("\n--- THREAD STATISTICS ---\n");
	printf("----------------------------------------------------\n");
	for (int i = 0; i < MaxGThreads; i++) {
		if (gt_table[i].state != Unused) {
			long long avgWaitTime = 0;
			if (gt_table[i].noSwitches > 0) {
				avgWaitTime = gt_table[i].totalWaitTime / gt_table[i].noSwitches;
			}
			printf("Thread #%d | Total runtime:  %lld us | Total wait time: %lld us | Min wait time: %lld us | Max wait time: %lld us ! | Avg wait time: %lld us\n",
				   i,
				   gt_table[i].totalTime,
				   gt_table[i].totalWaitTime,
				   gt_table[i].currentMinWaitTime,
				   gt_table[i].currentMaxWaitTime,
				   avgWaitTime
				   );
		}
	}
	printf("----------------------------------------------------\n");

	exit(EXIT_SUCCESS);
}

void gt_init(void) {
	memset(gt_table,0,sizeof(gt_table));
	gt_current = & gt_table[0];                                             // initialize current thread with thread #0
	gt_current -> state = Running;                                          // set current to running
	gettimeofday(&gt_current->last_start, NULL);
	signal(SIGALRM, gt_alarm_handle);                                       // register SIGALRM, signal from timer generated by alarm
	signal(SIGINT, gt_statistics_handler);
}


// exit thread
void __attribute__((noreturn)) gt_return(int ret) {
	if (gt_current != & gt_table[0]) {                                      // if not an initial thread,
		gt_current -> state = Unused;                                   // set current thread as unused// free the stack
		gt_schedule();                                                  // yield and make possible to switch to another thread
		assert(!"reachable");                                           // this code should never be reachable ... (if yes, returning function on stack was corrupted)
	}
	while (gt_schedule());                                                  // if initial thread, wait for other to terminate
	exit(ret);
}

// switch from one thread to other
bool gt_schedule(void) {
	struct gt * p;
	struct gt_context * old, * new;
	struct timeval now;
	gettimeofday(&now, NULL);

	gt_reset_sig(SIGALRM);
	if (gt_current->state == Running && gt_current->last_start.tv_sec > 0) {
		long long seconds = now.tv_sec - gt_current->last_start.tv_sec;
		long long microseconds = now.tv_usec - gt_current->last_start.tv_usec;

		long long elapsed_us = (seconds * 1000000LL) + microseconds;

		gt_current->totalTime += elapsed_us;

	}

	p = gt_current;

	while (p -> state != Ready) {                                           // iterate through gt_table[] until we find new thread in state Ready
		if (++p == & gt_table[MaxGThreads])                             // at the end rotate to the beginning
			p = & gt_table[0];
		if (p == gt_current)                                            // did not find any other Ready threads
			return false;
	}


	if (p->last_start.tv_sec > 0) {
		long long seconds = now.tv_sec - p->last_start.tv_sec;
		long long microseconds = now.tv_usec - p->last_start.tv_usec;
		long long wait_us = (seconds * 1000000LL) + microseconds;
		if (wait_us < 0) wait_us = 0;
		p->currentWaitTime = wait_us;
		p->totalWaitTime += wait_us;

	}
	if (p->currentWaitTime <= p->currentMinWaitTime || p->currentMinWaitTime == 0) {
		p->currentMinWaitTime = p->currentWaitTime;
	}
	if (p->currentWaitTime >= p->currentMaxWaitTime){
		p->currentMaxWaitTime = p->currentWaitTime;
	}

	p->noSwitches++;
	p->last_start = now;
	if (gt_current -> state != Unused)                                      // switch current to Ready and new thread found in previous loop to Running
		gt_current -> state = Ready;
	p -> state = Running;
	old = & gt_current -> ctx;                                              // prepare pointers to context of current (will become old)
	new = & p -> ctx;                                                       // and new to new thread found in previous loop
	gt_current = p;                                                         // switch current indicator to new thread
	gt_switch(old, new);                                                    // perform context switch (assembly in gtswtch.S)
	return true;
}

// return function for terminating thread
void gt_stop(void) {
	gt_return(0);
}

// create new thread by providing pointer to function that will act like "run" method
int gt_create(void( * f)(void)) {
	struct gt * p;

	for (p = & gt_table[0];; p++)                                           // find an empty slot
		if (p == & gt_table[MaxGThreads])                               // if we have reached the end, gt_table is full and we cannot create a new thread
			return -1;
		else if (p -> state == Unused)
			break;                                                  // new slot was found

	int idx = p - &gt_table[0];

	unsigned char *stack = stacks[idx];
	*(uint64_t * ) & stack[STACK_SIZE - 8] = (uint64_t) gt_stop;             //  put into the stack returning function gt_stop in case function calls return
	*(uint64_t * ) & stack[STACK_SIZE - 16] = (uint64_t) f;                  //  put provided function as a main "run" function
	p -> ctx.rsp = (uint64_t) & stack[STACK_SIZE - 16];                      //  set stack pointer
	p -> state = Ready;                                                                                           //  set state

	return 0;
}

// resets SIGALRM signal
void gt_reset_sig(int sig) {
	if (sig == SIGALRM) {
		alarm(0);                                                       // Clear pending alarms if any
	}

	sigset_t set;                                                           // Create signal set
	sigemptyset( & set);                                                    // Clear set
	sigaddset( & set, sig);                                                 // Set signal (we use SIGALRM)
	sigprocmask(SIG_UNBLOCK, & set, NULL);                                  // Fetch and change the signal mask

	if (sig == SIGALRM) {
		ualarm(500, 500);                                               // Schedule signal after given number of microseconds
	}
}

// uninterruptible sleep
int gt_uninterruptible_nanosleep(time_t sec, long nanosec) {
	struct timespec req;
	req.tv_sec = sec;
	req.tv_nsec = nanosec;

	do {
		if (0 != nanosleep( & req, & req)) {
			if (errno != EINTR)
				return -1;
		} else {
			break;
		}
	} while (req.tv_sec > 0 || req.tv_nsec > 0);
	return 0;
}
